default_job = "check"

[jobs.check]
command = ["cargo", "check", "--color", "always"]
need_stdout = false

[jobs.clippy]
command = ["cargo", "clippy", "--color", "always"]
need_stdout = false

[jobs.test]
command = [
    "cargo",
    "test",
    "tests",
    "--color",
    "always",
    "--test-threads=1",
    "--",
    "--nocapture",
    "--show-output",
]
need_stdout = true

[jobs.doc]
command = ["cargo", "doc", "--color", "always"]
need_stdout = false

[keybindings]
c = "job:check"
l = "job:clippy"
t = "job:test"
d = "job:doc"

# Ignore changes in test files and generated directories
[watch]
ignore_patterns = ["**/test_images/**", "**/*.tmp", "**/.DS_Store"]
