[package]
name = "image-deduper-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Core library for detecting and managing duplicate images"

[dependencies]

# Error handling
derive_more = { version = "2.0.1", features = ["from"] }
anyhow = { workspace = true }

# File handling and traversal
walkdir.workspace = true

# Image processing
libheif-rs.workspace = true
image.workspace = true

# Hashing
blake3.workspace = true
rustdct = "0.7.1"
ndarray = "0.16.1"

# Serialization
serde.workspace = true
serde_json.workspace = true

# Database
rusqlite = { version = "0.30", features = ["bundled"] }
r2d2 = "0.8"
r2d2_sqlite = "0.23"

# Concurrency and async
crossbeam.workspace = true
rayon.workspace = true
num_cpus = "1.16"

# Progress bars
indicatif = "0.17"

# HTTP client and async runtime (for examples)
tokio = { version = "1.36", features = ["full"] }
reqwest = { version = "0.11", features = ["blocking"] }

# Logging
log.workspace = true
env_logger.workspace = true
chrono = "0.4.40"
log4rs = "1.3.0"

[dev-dependencies]
image.workspace = true
tempfile = "3.18.0"
once_cell = "1.19.0"   # For lazy initialization in tests

[features]
default = []
