[package]
name = "image-deduper-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Core library for detecting and managing duplicate images"

[dependencies]
# File handling and traversal
walkdir.workspace = true
rayon.workspace = true
image.workspace = true
libheif-rs.workspace = true
blake3.workspace = true

# Serialization
serde.workspace = true
serde_json.workspace = true

# Database
rusqlite.workspace = true

# Error handling
derive_more = { version = "2.0.1", features = ["from"] }
anyhow = { workspace = true }

# Concurrency
crossbeam.workspace = true
num_cpus = "1.16"

# Progress bars
indicatif = "0.17"

# Logging
log.workspace = true
env_logger.workspace = true
ndarray = "0.16.1"
rustdct = "0.7.1"

# HTTP client and async runtime (for examples)
reqwest = { version = "0.11", features = ["blocking"] }
tokio = { version = "1.36", features = ["full"] }

[dev-dependencies]
image.workspace = true
tempfile = "3.18.0"
once_cell = "1.19.0"   # For lazy initialization in tests

[features]
default = []
