[package]
name = "image-deduper-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Core library for detecting and managing duplicate images"

[dependencies]
# File handling and traversal
walkdir.workspace = true
rayon.workspace = true
image.workspace = true
libheif-rs.workspace = true

# Hashing and comparison
blake3.workspace = true

# Serialization
serde.workspace = true
serde_json.workspace = true

# Database
rusqlite.workspace = true

# Error handling
derive_more = { version = "2.0.1", features = ["from"] }

# Concurrency
crossbeam.workspace = true

# Logging
log.workspace = true

[dev-dependencies]
image.workspace = true
tempfile = "3.18.0"

[[bin]]
name = "create-test-images"
path = "tests/discovery/create_test_images.rs"
